// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Component } from './fbsengine/component.js';
export { GameObject } from './fbsengine/game-object.js';
export { GameObjectPrefab } from './fbsengine/game-object-prefab.js';
export { Mesh } from './fbsengine/mesh.js';
export { Scene } from './fbsengine/scene.js';
export { SceneNode } from './fbsengine/scene-node.js';
export { Transform } from './fbsengine/transform.js';
export { Vec3 } from './fbsengine/vec3.js';
export { Vec4 } from './fbsengine/vec4.js';
