// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { GameObject } from '../fbsengine/game-object.js';
import { GameObjectPrefab } from '../fbsengine/game-object-prefab.js';


export enum SceneNode {
  NONE = 0,
  GameObjectPrefab = 1,
  GameObject = 2
}

export function unionToSceneNode(
  type: SceneNode,
  accessor: (obj:GameObject|GameObjectPrefab) => GameObject|GameObjectPrefab|null
): GameObject|GameObjectPrefab|null {
  switch(SceneNode[type]) {
    case 'NONE': return null; 
    case 'GameObjectPrefab': return accessor(new GameObjectPrefab())! as GameObjectPrefab;
    case 'GameObject': return accessor(new GameObject())! as GameObject;
    default: return null;
  }
}

export function unionListToSceneNode(
  type: SceneNode, 
  accessor: (index: number, obj:GameObject|GameObjectPrefab) => GameObject|GameObjectPrefab|null, 
  index: number
): GameObject|GameObjectPrefab|null {
  switch(SceneNode[type]) {
    case 'NONE': return null; 
    case 'GameObjectPrefab': return accessor(index, new GameObjectPrefab())! as GameObjectPrefab;
    case 'GameObject': return accessor(index, new GameObject())! as GameObject;
    default: return null;
  }
}
